ALTER TABLE products DROP COLUMN description RESTRICT;
ALTER TABLE products DROP COLUMN image_url RESTRICT;
ALTER TABLE products DROP COLUMN data RESTRICT;
ALTER TABLE products DROP COLUMN quantity RESTRICT;
ALTER TABLE products DROP COLUMN price RESTRICT;
ALTER TABLE products DROP COLUMN in_stock RESTRICT;
